"""Local run provenance. This file is never included in the submission archive."""

from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .config import Settings

METADATA_NAME = ".day09-run.json"


def _digest_files(root: Path, paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def source_snapshot(root: Path) -> dict[str, str]:
    revision = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, check=True, capture_output=True, text=True
    ).stdout.strip()
    files = [*root.glob("src/**/*.py"), *root.glob("contracts/schemas/*.json")]
    files += [*root.glob("inputs/*.json")]
    files += [root / name for name in ("pyproject.toml", "case-set.json")]
    if any(not path.is_file() for path in files):
        raise ValueError("source or input files are missing")
    return {"git_commit": revision, "content_sha256": _digest_files(root, files)}


def artifact_snapshot(root: Path) -> dict[str, str]:
    files = [*root.glob("outputs/*.json"), root / "traces" / "trace.jsonl"]
    if not files[-1].is_file():
        raise ValueError("trace is missing; rerun day09 run")
    return {"content_sha256": _digest_files(root, files)}


def key_fingerprint(team_key: str) -> str:
    return hashlib.sha256(team_key.encode()).hexdigest()[:8]


def write_run_metadata(root: Path, team_key: str, source: dict[str, str]) -> None:
    if source_snapshot(root) != source:
        raise ValueError("source or inputs changed during run; rerun day09 run")
    data: dict[str, Any] = {
        "source": source,
        "artifacts": artifact_snapshot(root),
        "team_key_fingerprint": key_fingerprint(team_key),
        "completed_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "output_count": len(list(root.glob("outputs/*.json"))),
    }
    path = root / METADATA_NAME
    staged = path.with_suffix(".tmp")
    staged.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    staged.replace(path)


def verify_run_metadata(root: Path) -> None:
    path = root / METADATA_NAME
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("run metadata is missing or invalid; rerun day09 run") from exc
    if data.get("source") != source_snapshot(root):
        raise ValueError("artifacts were generated by a different source revision; rerun day09 run")
    if data.get("artifacts") != artifact_snapshot(root) or data.get("output_count") != len(
        list(root.glob("outputs/*.json"))
    ):
        raise ValueError("artifacts changed since the run; rerun day09 run")
    current_key = Settings.load(root).team_api_key
    if data.get("team_key_fingerprint") != key_fingerprint(current_key):
        raise ValueError("Team API Key changed since the run; rerun day09 run")
